version: '3.8'

services:
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    
  backend:
    build: ./backend
    ports:
      - '80:80'
    volumes:
      - ./backend:/app
      - logs:/app/logs
      - /app/node_modules
    depends_on:
      - mongodb
  
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  logs:
